spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_ddl: true # 얘는 시스템아웃으로 찍음 -> 운영에선 이렇게 하면 안됨
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug  # 로거로 찍음
    org.hibernate.type: trace